const { PROFILE } = require('../utils/profiles');

const PERMISSIONS = Object.freeze({
  PEOPLE_WRITE: [PROFILE.ADMINISTRADOR, PROFILE.SECRETARIA],
  STUDENTS_WRITE: [PROFILE.ADMINISTRADOR, PROFILE.SECRETARIA],
  ATTENDANCE_ADMIN: [PROFILE.ADMINISTRADOR, PROFILE.SECRETARIA],
  ATTENDANCE_WRITE: [PROFILE.ADMINISTRADOR, PROFILE.SECRETARIA, PROFILE.PROFESSOR],
  OFFERS_WRITE: [PROFILE.ADMINISTRADOR, PROFILE.SECRETARIA, PROFILE.FINANCEIRO]
});

module.exports = {
  PERMISSIONS
};
